set_property PACKAGE_PIN E16 [get_ports rst_n]
set_property PACKAGE_PIN E15 [get_ports clk]
set_property PACKAGE_PIN D16 [get_ports sync_in]
set_property PACKAGE_PIN A13 [get_ports pad_spi_sync_o]
set_property PACKAGE_PIN G17 [get_ports pad_spi_clk_o]
set_property PACKAGE_PIN P14 [get_ports pad_spi_din]
set_property PACKAGE_PIN T15 [get_ports pad_spi_dout]
set_property PACKAGE_PIN J14 [get_ports {tx_din[7]}]
set_property PACKAGE_PIN M16 [get_ports {tx_din[5]}]
set_property PACKAGE_PIN N16 [get_ports {tx_din[4]}]
set_property PACKAGE_PIN K18 [get_ports {tx_din[3]}]
set_property PACKAGE_PIN L15 [get_ports {tx_din[2]}]
set_property PACKAGE_PIN M14 [get_ports {tx_din[1]}]
set_property PACKAGE_PIN N14 [get_ports {tx_din[0]}]
set_property PACKAGE_PIN N18 [get_ports {tx_din[6]}]
set_property PACKAGE_PIN T17 [get_ports {rx_dout[7]}]
set_property PACKAGE_PIN T18 [get_ports {rx_dout[5]}]
set_property PACKAGE_PIN V16 [get_ports {rx_dout[4]}]
set_property PACKAGE_PIN T13 [get_ports {rx_dout[3]}]
set_property PACKAGE_PIN V12 [get_ports {rx_dout[2]}]
set_property PACKAGE_PIN U16 [get_ports {rx_dout[1]}]
set_property PACKAGE_PIN R17 [get_ports {rx_dout[0]}]
set_property PACKAGE_PIN T12 [get_ports {rx_dout[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports]