vivado -mode tcl -source ./scripts/vvd_encrypt.tcl
# check the encrypted file
echo "====read single key code encrypted by vivado"
xvlog ./src/adder.vp
echo "====read mult key code encrypted by vivado"
xvlog ./src/adder_mult_key.vp

echo "====read single questa key code encrypted by vivado"
xvlog ./src/adder_wh_questakey.vp

echo "====read single vvd key code encrypted by vivado"
xvlog ./src/adder_wh_vvdkey.vp

#check the encypted files by questa

echo "====read single key v2 code encrypted by questa"
xvlog ../questa_prj/encrypted_src/adder_v2.vp

echo "====read single key code encrypted by questa"
xvlog ../questa_prj/encrypted_src/adder.vp

echo "====read embedded single vvdkey code encrypted by questa"
xvlog ../questa_prj/encrypted_src/adder_wh_vvdkey.vp

echo "====read embedded single questa key encrypted by questa"
xvlog ../questa_prj/encrypted_src/adder_wh_questakey.vp

echo "====read embedded multi key code generated by questa"
xvlog ../questa_prj/encrypted_src/adder_wh_key.vp
echo "====read mult key code generated by questa"
xvlog ../questa_prj/encrypted_src/adder_mult_key.vp
