set_property PACKAGE_PIN E16 [get_ports rst]

set_property IOSTANDARD LVCMOS25 [get_ports rst]
set_property IOSTANDARD LVDS_25 [get_ports lvds*]

set_property PACKAGE_PIN P4 [get_ports lvds_clkin_p]
set_property PACKAGE_PIN P3 [get_ports lvds_clkin_n]
set_property PACKAGE_PIN K3 [get_ports {lvds_din_p[0]}]
set_property PACKAGE_PIN L2 [get_ports {lvds_din_n[0]}]
set_property PACKAGE_PIN K2 [get_ports {lvds_din_p[1]}]
set_property PACKAGE_PIN K1 [get_ports {lvds_din_n[1]}]
set_property PACKAGE_PIN J5 [get_ports {lvds_din_p[2]}]
set_property PACKAGE_PIN J4 [get_ports {lvds_din_n[2]}]
set_property PACKAGE_PIN K6 [get_ports {lvds_din_p[3]}]
set_property PACKAGE_PIN K5 [get_ports {lvds_din_n[3]}]
set_property PACKAGE_PIN M6 [get_ports {lvds_dout_p[0]}]
set_property PACKAGE_PIN N6 [get_ports {lvds_dout_n[0]}]
set_property PACKAGE_PIN M2 [get_ports {lvds_dout_p[1]}]
set_property PACKAGE_PIN M1 [get_ports {lvds_dout_n[1]}]
set_property PACKAGE_PIN L4 [get_ports {lvds_dout_p[3]}]
set_property PACKAGE_PIN L3 [get_ports {lvds_dout_n[3]}]
set_property PACKAGE_PIN L5 [get_ports {lvds_dout_p[2]}]
set_property PACKAGE_PIN M5 [get_ports {lvds_dout_n[2]}]
set_property PACKAGE_PIN T4 [get_ports lvds_clkout_p]
set_property PACKAGE_PIN T3 [get_ports lvds_clkout_n]
